spring.application.name=tournament-console

# Oracle connection (adjust host/port/SID/service name)
spring.datasource.url=jdbc:oracle:thin:@<fsktmdbora.upm.edu.my>:<1521>/<FSKTM>
spring.datasource.username=<D230477>
spring.datasource.password=<230477>
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# Use 'validate' once the schema above is created manually (recommended for this project)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf (disable cache during development)
spring.thymeleaf.cache=false

server.port=8080
